### ISSUE TITLE
Problems exporting multi-objects (2.79)

### ISSUE THREAD

**Issue by nashmuhandes** [nashmuhandes/io_export_gzdoom_md3#7]
Sending example file to your PM box on the ZDoom forum @Talon1024 

It seems when I select all and attempt to export the model, the vertices end up corrupted in-game.

**Comment by nashmuhandes** [comment]
Fixed it on the modeling side - instead of using shape keys for the "gun" and "sword" attachments - create dedicated bones for each of them on the main character's armature, and parent them to the bones instead.

Shape key animation (without usage of bones) usually works perfectly for a single object, so I'll probably just leave this open in case there's an interest to look into this in future.

**Comment by Talon1024** [comment]
I don't know what the actual cause of this bug is, but my best guess is the order of `BlenderSurface.vertex_refs` not being consistent. I just tried to fix that by using an `OrderedDict` (remembers the order in which key-value pairs are inserted) instead of a regular unordered dict.

Also, I haven't been able to reproduce this on later Blender versions, but the `dict` in versions of Python later than 3.5 (the Python version built into Blender 2.79b) is basically an `OrderedDict` because it preserves the order in which key-value pairs are inserted.

I think, with that change, I'm able to consistently export ElderJamPlayer.md3 without it being corrupted.
